version: '3.6'
services:
  es-db:
    image: elasticsearch:7.13.3
    container_name: es-db
    ports:
      - 9200:9200
      - 9300:9300
    environment: 
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - network.host=0.0.0.0
      - discovery.zen.minimum_master_nodes=1
    volumes:
        - ./elasticsearch-data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
  
  kibana:
    image: kibana:7.13.3
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on: 
      - es-db
    environment:
      - ELASTICSEARCH_HOSTS=["http://es-db:9200"]
networks:
  elastic:
    driver: bridge
